#!/bin/sh
SITE="$1"

# Update home directory:
usermod -d /var/www/ vagrant

apt-get -y update

# build helper
apt-get install -y curl build-essential git-core

# apache
apt-get install -y apache2

# mysql
if [ -z `which mysql` ]; then
  DEBIAN_FRONTEND=noninteractive  apt-get install -y mysql-server
  apt-get install -y mysql-client
  mysqladmin -u root password flow
fi

# PHP
apt-get install -y php5 php5-gd php5-curl php5-mcrypt php5-xdebug php5-mysql

# Drush
apt-get install -y drush

# Gems
if [ -z `which compass` ]; then
  apt-get install -y rubygems
  gem install compass-sourcemaps --pre
fi

# Vim
if [ -z `which vim` ]; then
  apt-get intall -y vim
fi

# Link /var/www
if [ ! -d "/var/www/private" ]; then
  rm -rf /var/www/
  ln -s /vagrant /var/www
  mkdir -p /var/www/private
  chown -R www-data:www-data /var/www
fi

# Sync configuration files
rsync --keep-dirlinks -recursive --perms --owner --group /vagrant/vagrant_setup/root/ /
chown vagrant /home/vagrant

# SSH config
if [ ! -f "/home/vagrant/.ssh/id_rsa" ]; then
  sudo -u vagrant -H cp /vagrant/vagrant_setup/ssh/* /home/vagrant/.ssh/
  sudo -u vagrant -H chmod 740 /home/vagrant
  sudo -u vagrant -H chmod 740 /home/vagrant/.ssh
  sudo -u vagrant -H chmod 600 /home/vagrant/.ssh/id_rsa
  sudo -u vagrant -H chmod 740 /home/vagrant/.ssh/authorized_keys
fi

# Use the gateway (host) as xdebug host
route -n | grep 'UG    0' | awk '{print "\nxdebug.remote_host = " $2}' >> /etc/php5/conf.d/xdebug.ini

# Tell drupal which site to use
if [ -n $SITE ]; then
  echo "<?php
  // Generated by vagrant config.sh
  \$sites['localhost'] = '$SITE';" > /var/www/htdocs/sites/sites-local.php
  if [ -d "/var/www/htdocs/sites/$SITE" ]; then
    cp /var/www/htdocs/sites/default/settings-local.php "/var/www/htdocs/sites/$SITE/settings-local.php"
  fi
fi

a2dissite default
a2ensite vagrant

a2enmod rewrite

pecl install uploadprogress
a2enmod uploadprogress

# install .so extensions
find /usr/lib/php5/ | grep xdebug.so | awk '{print "\nzend_extension = " $1 "\n"}' >> /etc/php5/conf.d/xdebug.ini
find /usr/lib/php5/ | grep uploadprogress.so | awk '{print "\nextension = " $1}' >> /etc/php5/apache2/php.ini

# Restart apache
/etc/init.d/apache2 restart

# Create empty database
mysql -uroot -pflow -e "DROP DATABASE IF EXISTS drupal;"
mysql -uroot -pflow -e "CREATE DATABASE drupal;"
mysql -uroot -pflow -e "GRANT ALL ON drupal.* TO flowconcept@localhost IDENTIFIED BY 'flow'"

# Get current database
sudo -u vagrant -H drush sql-sync @vagrant.staging @vagrant.dev --no-cache -y

# Uncomment to use sync instead of stage proxy
# drush rsync @vagrant.staging:%files/ @vagrant.dev:sites/default/files/ -y

sudo -u vagrant -H drush @vagrant.dev cc all
sudo -u vagrant -H drush @vagrant.dev en flow_dev -y
sudo -u vagrant -H drush @vagrant.dev compass compile
sudo -u vagrant -H drush @vagrant.dev ev 'module_load_include("inc", "system", "system.admin"); $form_state = array(); drupal_form_submit("system_theme_settings", $form_state, "flowconcept");'

echo "Done starting up $SITE"