# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration overrides
#$config = {
#  box: "opscode-debian-7.4",
#  box_url: "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.4_chef-provisionerless.box",
#  synced_folder_type: "nfs"
#}

require "./vagrant/vagrant.rb"
