#!/bin/sh

SITE="$1"

# Sync configuration files
rsync --keep-dirlinks -recursive --perms --owner --group /vagrant/vagrant/config/root/ /
chown -R vagrant /home/vagrant

# Tell drupal which site to use
if [ -n $SITE ]; then
  echo "<?php
  // Generated by vagrant config.sh
  \$sites['localhost'] = '$SITE';" > /var/www/htdocs/sites/sites-local.php
  if [ -d "/var/www/htdocs/sites/$SITE" ]; then
    cp /var/www/htdocs/sites/default/settings.local.php "/var/www/htdocs/sites/$SITE/settings.local.php"
  fi
fi

# Drop local database
sudo -u vagrant -H drush --yes @vagrant.dev sql-drop
# Get current database
sudo -u vagrant -H drush --yes --no-cache sql-sync @vagrant.staging @vagrant.dev

# Uncomment to use sync instead of stage proxy
sudo -u vagrant -H drush --yes rsync @vagrant.staging:%files @vagrant.dev:%files

sudo -u vagrant -H drush @vagrant.dev cc all
sudo -u vagrant -H drush @vagrant.dev cr

echo "Done provisioning site $SITE"
